[package]
name = "mobile-dev-ios-fps"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
idevice = { git = "https://github.com/jkcoxson/idevice", rev = "a64b8867815b3da17b5c927531bdba877e8456ef", default-features = false, features = ["ring", "usbmuxd", "core_device_proxy", "tunnel_tcp_stack", "dvt", "rsd"] }
plist = "1.8"
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "signal", "io-std", "io-util"] }

[profile.release]
lto = true
strip = "symbols"
codegen-units = 1
