import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {build,transform} from 'esbuild';
import {JSDOM} from 'jsdom';
import * as React from 'react';
import {createRoot} from 'react-dom/client';

const require=createRequire(import.meta.url),babel=require('@babel/core'),plugin=require('../src/server/app-flow/instrumentation-plugin.cjs');

test('instrumented preview preserves real props/context, isolates state, suppresses app effects, and restores',async t=>{
  const dom=new JSDOM('<div id="root"></div>');
  const saved={window:globalThis.window,document:globalThis.document,IS_REACT_ACT_ENVIRONMENT:globalThis.IS_REACT_ACT_ENVIRONMENT};
  Object.assign(globalThis,{window:dom.window,document:dom.window.document,IS_REACT_ACT_ENVIRONMENT:true});
  t.after(()=>{Object.assign(globalThis,saved);dom.window.close();});
  const context=vm.createContext({setTimeout,clearTimeout,console});
  const bundle=await build({entryPoints:['src/server/app-flow/instrumentation-client.js'],bundle:true,write:false,format:'cjs',platform:'node',external:['react','react-native']});
  const module={exports:{} as any};
  const native={View:({children,style}:any)=>React.createElement('div',{style},children)};
  context.module=module;context.exports=module.exports;context.require=(name:string)=>name==='react'?React:native;
  vm.runInContext(bundle.outputFiles[0].text,context);
  const client=module.exports;
  const markerOwner={id:'key-test',pending:new Map()};
  const plainMarker=client.entry(markerOwner,'plain',React.createElement('span'));
  assert.equal(plainMarker.key,null,'An unkeyed element must stay unkeyed, not receive the string null');
  const keyedMarker=client.entry(markerOwner,'keyed',React.createElement('span',{key:'row'}));
  assert.equal(keyedMarker.key,'row','Repeated source markers preserve each row key');
  const inputRef=React.createRef(),element=React.createElement('input',{key:'field',ref:inputRef,autoFocus:true});
  const wrapped=client.input(element);assert.equal(wrapped.key,'field');assert.equal(wrapped.props.element,element);assert.equal(wrapped.props.element.props.ref,inputRef);
  const source=`import * as React from 'react';
export const Data=React.createContext('missing');
export let effects=0,subscriptions=0;
const subscribe=()=>{subscriptions++;return ()=>{}};
const read=()=>"real snapshot";
export function Screen({label}) {
  const [step,setStep]=React.useState('first');
  const data=React.useContext(Data);
  React.useSyncExternalStore(subscribe,read,read);
  React.useEffect(()=>{effects++},[step]);
  if(step === 'broken') throw new Error('Preview failure');
  return <><button autoFocus data-step={step}/><span>{label}:{data}:{step}</span></>;
}
export function RootNavigator(){return <Data.Provider value="local-context"><Screen label="real-prop"/></Data.Provider>;}`;
  const lines=source.split('\n'),line=lines.findIndex(value=>value.includes('React.useState'))+1;
  const manifest={sourceHash:'hash',files:{'screen.jsx':{hash:createHash('sha256').update(source).digest('hex'),states:[{id:'step',owner:'Screen',line,column:lines[line-1].indexOf('React.useState')}],controls:[],hosts:['RootNavigator']}}};
  const prepared=babel.transformSync(source,{filename:'/app/screen.jsx',configFile:false,babelrc:false,parserOpts:{plugins:['jsx']},plugins:[[plugin,{enabled:true,projectRoot:'/app',client:'flow-client',manifest}]]}).code;
  const compiled=await transform(prepared,{loader:'jsx',format:'cjs'});
  const screenModule={exports:{} as any};context.module=screenModule;context.exports=screenModule.exports;context.require=(name:string)=>name==='react'?React:client;
  vm.runInContext(compiled.code,context);const app=screenModule.exports;
  const reported:any[]=[];
  const root=createRoot(dom.window.document.getElementById('root')!,{onCaughtError:error=>reported.push(error)});
  const nativeRoot=(root as any)._internalRoot, originalCaught=nativeRoot.onCaughtError;
  context.__REACT_DEVTOOLS_GLOBAL_HOOK__={renderers:new Map([[1,{rendererPackageName:'react-native-renderer'}]]),getFiberRoots:()=>new Set([nativeRoot])};
  t.after(async()=>{await React.act(()=>root.unmount());});
  await React.act(()=>root.render(React.createElement(React.StrictMode,null,React.createElement(app.Data.Provider,{value:'real-context'},React.createElement(app.RootNavigator)))));
  const registry=client.registry,live=registry.find('step');
  assert.ok(live);assert.equal(live.value.tuple[0],'first');const beforeEffects=app.effects,beforeSubscriptions=app.subscriptions;
  const focused=dom.window.document.activeElement;assert.equal(focused?.getAttribute('data-step'),'first');
  await React.act(()=>registry.project({source:live.owner.source,owner:live.owner,site:'step',value:'second'}));
  const preview=registry.find('step');assert.ok(preview.owner.preview);assert.equal(preview.value.tuple[0],'second');
  assert.equal(live.value.tuple[0],'first');assert.equal(app.effects,beforeEffects);assert.equal(app.subscriptions,beforeSubscriptions,'App-owned subscriptions stay contained in the copied form');
  assert.match(dom.window.document.body.textContent!,/real-prop:local-context:second/);
  assert.equal(dom.window.document.activeElement,focused,'A copied autoFocus input must not open system keyboard or autofill UI');
  await React.act(()=>preview.value.tuple[1]('third'));
  assert.equal(registry.find('step').value.tuple[0],'third');assert.equal(app.effects,beforeEffects);
  await React.act(()=>registry.unproject());
  assert.equal(registry.find('step').value.tuple[0],'first');
  assert.equal(dom.window.document.body.textContent,'real-prop:local-context:first');
  assert.equal(nativeRoot.onCaughtError,originalCaught);
  await React.act(()=>registry.project({source:live.owner.source,owner:live.owner,site:'step',value:'broken'}));
  assert.match(registry.projection.error,/failed to render/);
  assert.deepEqual(reported,[],'Only the temporary boundary contains its own render error');
  await React.act(()=>registry.unproject());
  assert.equal(nativeRoot.onCaughtError,originalCaught);
  assert.equal(dom.window.document.body.textContent,'real-prop:local-context:first');
  assert.equal(app.effects,beforeEffects);
  await React.act(()=>root.unmount());assert.equal(registry.inventory().owners,0);
});
